name: Deploy to EC2

on:
  push:
    branches:
      - main   # Change this if you use a different branch for production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: List the contents of the current directory (for debugging)
      - name: List directory contents
        run: ls -la

      # Step 3: Change directory and publish .NET Core API in the same run step
      - name: Publish .NET Core API
        run: |
          cd TrackMyBudget
          ls -la  # To confirm we're in the right directory
          dotnet publish -c Release -o ./publish

      # Step 4: Copy the published files to the EC2 instance using SCP
      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} -r ./TrackMyBudget/TrackMyBudget/publish/* ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/TrackMyBudget

      # Step 5: SSH into the EC2 instance and restart the service
      - name: SSH into EC2 and restart service
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo systemctl restart trackmybudget"
