name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log the current directory (useful for debugging)
      - name: Log current directory
        run: pwd

      # Step 3: List the contents of the current directory
      - name: List directory contents
        run: ls -la

      # Step 4: Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      # Step 5: Publish the .NET Core API (you might need to update the path to your project)
      - name: Publish .NET Core API
        run: dotnet publish ./src/TrackMyBudget/TrackMyBudget.csproj -c Release -o ./publish

      # Step 6: Copy files to EC2 using SCP
      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} -r ./publish/* ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/TrackMyBudget

      # Step 7: SSH into EC2 and restart the service
      - name: SSH into EC2 and restart service
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo systemctl restart trackmybudget"
